
------------------------ 2016-05-18 23:30:32 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2e580c3f rejected from java.util.concurrent.ScheduledThreadPoolExecutor@168c13de[Shutting down, pool size = 4, active threads = 1, queued tasks = 197, completed tasks = 35802]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4650)
	at client.MapleCharacter$5.run(MapleCharacter.java:4654)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-24 20:56:06 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4878b258 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@6c04d493[Shutting down, pool size = 4, active threads = 1, queued tasks = 22, completed tasks = 4410]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-26 17:12:01 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@11c4c272 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@cb9d37b[Shutting down, pool size = 4, active threads = 1, queued tasks = 16, completed tasks = 11718]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 00:31:50 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@26233975 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@529143e2[Shutting down, pool size = 4, active threads = 1, queued tasks = 54, completed tasks = 71791]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:10 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1fb08616 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 1, queued tasks = 78, completed tasks = 162512]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:10 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@27195fb7 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 1, queued tasks = 77, completed tasks = 162513]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@5c95052 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 73, completed tasks = 162514]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@63b83a75 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 73, completed tasks = 162514]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@54060a78 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 73, completed tasks = 162514]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@58997760 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 73, completed tasks = 162514]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3ad82ff0 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 71, completed tasks = 162516]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@473353be rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 71, completed tasks = 162516]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@29644e64 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 69, completed tasks = 162518]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@78569c76 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 69, completed tasks = 162518]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@237442dc rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 68, completed tasks = 162519]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@72041c28 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 66, completed tasks = 162521]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@602aa82a rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 3, queued tasks = 66, completed tasks = 162521]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@5f256edd rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 65, completed tasks = 162522]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@12919ff8 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 64, completed tasks = 162523]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3517107b rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 62, completed tasks = 162525]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@32401edc rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 62, completed tasks = 162525]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@8f8186 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 59, completed tasks = 162528]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@67df034e rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 61, completed tasks = 162526]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4d8084b3 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 59, completed tasks = 162528]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@55acb8b4 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 57, completed tasks = 162530]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3e925d5d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 57, completed tasks = 162530]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7b2fa4c2 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 56, completed tasks = 162531]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@74e9fbbc rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 55, completed tasks = 162532]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@272c34be rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 3, queued tasks = 51, completed tasks = 162536]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7f0af063 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 54, completed tasks = 162533]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@473aba09 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 51, completed tasks = 162536]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7953bab5 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 51, completed tasks = 162536]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@101baa3a rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 4, queued tasks = 49, completed tasks = 162538]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@844ce19 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 3, queued tasks = 49, completed tasks = 162539]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-27 18:35:11 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7d754b60 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7e331e9a[Shutting down, pool size = 4, active threads = 1, queued tasks = 48, completed tasks = 162542]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-28 00:44:35 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6e64cdb5 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1bfd5eb2[Shutting down, pool size = 4, active threads = 1, queued tasks = 50, completed tasks = 60534]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-28 00:44:36 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@70099379 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1bfd5eb2[Shutting down, pool size = 4, active threads = 1, queued tasks = 49, completed tasks = 60535]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-28 00:44:37 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@639c3d80 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1bfd5eb2[Shutting down, pool size = 4, active threads = 1, queued tasks = 48, completed tasks = 60536]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-28 00:44:37 ------------------------

------------------------ 2016-08-28 00:44:37 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@11944dda rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1bfd5eb2[Shutting down, pool size = 4, active threads = 2, queued tasks = 46, completed tasks = 60537]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1f832c3a rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1bfd5eb2[Shutting down, pool size = 4, active threads = 2, queued tasks = 46, completed tasks = 60537]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-28 00:44:37 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2b11a441 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1bfd5eb2[Shutting down, pool size = 4, active threads = 1, queued tasks = 45, completed tasks = 60539]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-28 00:44:37 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6ed2a50c rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1bfd5eb2[Shutting down, pool size = 4, active threads = 1, queued tasks = 44, completed tasks = 60540]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4728)
	at client.MapleCharacter$5.run(MapleCharacter.java:4732)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:43 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6a25b3fe rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 165, completed tasks = 428784]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:43 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2a502bad rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 164, completed tasks = 428785]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:43 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@48cfaf36 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 163, completed tasks = 428786]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:44 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@afed67a rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 162, completed tasks = 428787]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:45 ------------------------

------------------------ 2016-08-29 00:26:45 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4c62ccd6 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 160, completed tasks = 428788]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6a761cc7 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 160, completed tasks = 428788]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:46 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@361a2942 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 158, completed tasks = 428790]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:46 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@21bfc8d5 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 158, completed tasks = 428790]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:46 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4ee9bf3d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 157, completed tasks = 428792]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:46 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@76c02576 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 156, completed tasks = 428793]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:46 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@13a2c4b2 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 155, completed tasks = 428794]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:46 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6c2cb553 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 154, completed tasks = 428795]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:46 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@48c8245c rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 153, completed tasks = 428796]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@631e7e58 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 152, completed tasks = 428797]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2cabdd06 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 151, completed tasks = 428798]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@26c2ae2e rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 150, completed tasks = 428799]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@8382e4d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 149, completed tasks = 428799]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@35fbe96a rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 147, completed tasks = 428801]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2abe97fd rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 146, completed tasks = 428802]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4ef9c481 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 145, completed tasks = 428803]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@55a1e476 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 144, completed tasks = 428804]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@31125dbd rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 143, completed tasks = 428805]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@df97df2 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 142, completed tasks = 428806]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@2067c572 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 148, completed tasks = 428800]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@188af81e rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 141, completed tasks = 428807]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1f55117 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 139, completed tasks = 428809]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@109ebe02 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 139, completed tasks = 428809]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@5e354f98 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 138, completed tasks = 428811]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@59acb48d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 137, completed tasks = 428812]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@56279757 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 136, completed tasks = 428813]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@119e53af rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 135, completed tasks = 428814]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@5b9db505 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 134, completed tasks = 428815]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@28b59830 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 133, completed tasks = 428816]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:47 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@34e9fa8f rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 132, completed tasks = 428817]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:48 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@571a552e rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 131, completed tasks = 428818]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:48 ------------------------

------------------------ 2016-08-29 00:26:48 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3a66aec8 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 129, completed tasks = 428819]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@61226eb1 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 129, completed tasks = 428819]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:48 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@bd0a3e0 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 128, completed tasks = 428821]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:48 ------------------------

------------------------ 2016-08-29 00:26:48 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@26ded004 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 127, completed tasks = 428822]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:48 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3b57a42e rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 126, completed tasks = 428822]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:48 ------------------------

------------------------ 2016-08-29 00:26:48 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7951f58f rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 3, queued tasks = 123, completed tasks = 428824]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@73d0bd82 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 3, queued tasks = 123, completed tasks = 428824]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:48 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@5ef641ad rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 125, completed tasks = 428823]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@130e0aa4 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 122, completed tasks = 428826]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@5c0c96e6 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 120, completed tasks = 428829]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1269ccd2 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 119, completed tasks = 428830]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@27f970a9 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 118, completed tasks = 428831]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@67e16e9e rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 117, completed tasks = 428832]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4406f94c rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 116, completed tasks = 428833]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4d86a2b1 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 115, completed tasks = 428834]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@16c3d7c2 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 114, completed tasks = 428835]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4c6aa682 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 113, completed tasks = 428836]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@74d96eb0 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 111, completed tasks = 428837]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6ef220be rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 111, completed tasks = 428837]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@34e43599 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 3, queued tasks = 110, completed tasks = 428837]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@727aeaef rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 4, queued tasks = 109, completed tasks = 428837]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7632f1e rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 4, queued tasks = 107, completed tasks = 428839]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1ca4895 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 4, queued tasks = 108, completed tasks = 428838]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------

------------------------ 2016-08-29 00:26:51 ------------------------

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3118ea5b rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 4, queued tasks = 106, completed tasks = 428840]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1fee7305 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 4, queued tasks = 104, completed tasks = 428842]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7c148739 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 4, queued tasks = 105, completed tasks = 428841]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@771a8387 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 3, queued tasks = 103, completed tasks = 428844]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@4342856 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 102, completed tasks = 428847]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@55103313 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 100, completed tasks = 428848]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1a895006 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 100, completed tasks = 428848]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:51 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@3f4ef306 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 99, completed tasks = 428850]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:52 ------------------------

------------------------ 2016-08-29 00:26:52 ------------------------

------------------------ 2016-08-29 00:26:52 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@46650f03 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 97, completed tasks = 428851]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@704e4312 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 3, queued tasks = 95, completed tasks = 428851]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@14bcb210 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 2, queued tasks = 97, completed tasks = 428851]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:52 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@22158c58 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 4, queued tasks = 95, completed tasks = 428851]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

------------------------ 2016-08-29 00:26:52 ------------------------
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@34828e37 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@514c1f23[Shutting down, pool size = 4, active threads = 1, queued tasks = 94, completed tasks = 428855]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source)
	at server.Timer.schedule(Timer.java:182)
	at client.MapleCharacter.checkBerserk(MapleCharacter.java:4747)
	at client.MapleCharacter$5.run(MapleCharacter.java:4751)
	at server.Timer$LoggingSaveRunnable.run(Timer.java:202)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
